
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  


steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName:  'Install Node.js'


- script: |
    install
    run test:ci
  displayName: 'Run Cypress tests'
  
#Publsih test results

# Step 5: Publish Cypress test results in JUnit format
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/cypress/reports/*.xml'  
    testRunTitle: 'Cypress Mochawesome Test Results'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testResultsFormat: 'JUnit'
  displayName: 'Publsih cypress test results'

