trigger:
  - main # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest' # Specify the build agent

steps:
  # Step 1: Install dependencies
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x' # Specify Node.js version
    displayName: 'Install Node.js'
  
  - task: CacheBeta@1
    inputs:
      key: npm | package-lock.json
      path: /home/vsts/.npm
      restoreKeys: npm | package-lock.json
  - task: CacheBeta@1
    inputs:
      key: cy | package-lock.json
      path: /home/vsts/.cache/Cypress
      restoreKeys: cy | package-lock.json

  # Step 2: Install project dependencies
  - script: npm install
    displayName: 'Install dependencies'

  # Step 3: Run Cypress tests
  - script: run test:ci
    displayName: 'Run Cypress tests'

  # Step 4: Publish test results to Azure DevOps
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results/*.xml' # Path to the JUnit XML results
      testRunTitle: 'Cypress Test Run'
    displayName: 'Publish Cypress Test Results'
